// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: middleware/circuitbreaker/v1/circuitbreaker.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CircuitBreaker middleware config.
type CircuitBreaker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Trigger:
	//
	//	*CircuitBreaker_SuccessRatio
	//	*CircuitBreaker_Ratio
	Trigger isCircuitBreaker_Trigger `protobuf_oneof:"trigger"`
}

func (x *CircuitBreaker) Reset() {
	*x = CircuitBreaker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_middleware_circuitbreaker_v1_circuitbreaker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CircuitBreaker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CircuitBreaker) ProtoMessage() {}

func (x *CircuitBreaker) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_circuitbreaker_v1_circuitbreaker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CircuitBreaker.ProtoReflect.Descriptor instead.
func (*CircuitBreaker) Descriptor() ([]byte, []int) {
	return file_middleware_circuitbreaker_v1_circuitbreaker_proto_rawDescGZIP(), []int{0}
}

func (m *CircuitBreaker) GetTrigger() isCircuitBreaker_Trigger {
	if m != nil {
		return m.Trigger
	}
	return nil
}

func (x *CircuitBreaker) GetSuccessRatio() *SuccessRatio {
	if x, ok := x.GetTrigger().(*CircuitBreaker_SuccessRatio); ok {
		return x.SuccessRatio
	}
	return nil
}

func (x *CircuitBreaker) GetRatio() int64 {
	if x, ok := x.GetTrigger().(*CircuitBreaker_Ratio); ok {
		return x.Ratio
	}
	return 0
}

type isCircuitBreaker_Trigger interface {
	isCircuitBreaker_Trigger()
}

type CircuitBreaker_SuccessRatio struct {
	SuccessRatio *SuccessRatio `protobuf:"bytes,1,opt,name=success_ratio,json=successRatio,proto3,oneof"`
}

type CircuitBreaker_Ratio struct {
	Ratio int64 `protobuf:"varint,2,opt,name=ratio,proto3,oneof"`
}

func (*CircuitBreaker_SuccessRatio) isCircuitBreaker_Trigger() {}

func (*CircuitBreaker_Ratio) isCircuitBreaker_Trigger() {}

type SuccessRatio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success float64              `protobuf:"fixed64,1,opt,name=success,proto3" json:"success,omitempty"`
	Request int32                `protobuf:"varint,2,opt,name=request,proto3" json:"request,omitempty"`
	Bucket  int32                `protobuf:"varint,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Window  *durationpb.Duration `protobuf:"bytes,4,opt,name=window,proto3" json:"window,omitempty"`
}

func (x *SuccessRatio) Reset() {
	*x = SuccessRatio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_middleware_circuitbreaker_v1_circuitbreaker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuccessRatio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessRatio) ProtoMessage() {}

func (x *SuccessRatio) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_circuitbreaker_v1_circuitbreaker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessRatio.ProtoReflect.Descriptor instead.
func (*SuccessRatio) Descriptor() ([]byte, []int) {
	return file_middleware_circuitbreaker_v1_circuitbreaker_proto_rawDescGZIP(), []int{1}
}

func (x *SuccessRatio) GetSuccess() float64 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *SuccessRatio) GetRequest() int32 {
	if x != nil {
		return x.Request
	}
	return 0
}

func (x *SuccessRatio) GetBucket() int32 {
	if x != nil {
		return x.Bucket
	}
	return 0
}

func (x *SuccessRatio) GetWindow() *durationpb.Duration {
	if x != nil {
		return x.Window
	}
	return nil
}

var File_middleware_circuitbreaker_v1_circuitbreaker_proto protoreflect.FileDescriptor

var file_middleware_circuitbreaker_v1_circuitbreaker_proto_rawDesc = []byte{
	0x0a, 0x31, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x2f, 0x63, 0x69, 0x72,
	0x63, 0x75, 0x69, 0x74, 0x62, 0x72, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x63,
	0x69, 0x72, 0x63, 0x75, 0x69, 0x74, 0x62, 0x72, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x21, 0x6e, 0x65, 0x78, 0x74, 0x2e, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65,
	0x77, 0x61, 0x72, 0x65, 0x2e, 0x63, 0x69, 0x72, 0x63, 0x75, 0x69, 0x74, 0x62, 0x72, 0x65, 0x61,
	0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8b, 0x01, 0x0a, 0x0e, 0x43, 0x69, 0x72, 0x63, 0x75,
	0x69, 0x74, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x12, 0x56, 0x0a, 0x0d, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x5f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2f, 0x2e, 0x6e, 0x65, 0x78, 0x74, 0x2e, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61,
	0x72, 0x65, 0x2e, 0x63, 0x69, 0x72, 0x63, 0x75, 0x69, 0x74, 0x62, 0x72, 0x65, 0x61, 0x6b, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x61, 0x74, 0x69,
	0x6f, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x61, 0x74, 0x69,
	0x6f, 0x12, 0x16, 0x0a, 0x05, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x48, 0x00, 0x52, 0x05, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x42, 0x09, 0x0a, 0x07, 0x74, 0x72, 0x69,
	0x67, 0x67, 0x65, 0x72, 0x22, 0x8d, 0x01, 0x0a, 0x0c, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x52, 0x61, 0x74, 0x69, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x12, 0x31, 0x0a, 0x06, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x77, 0x69,
	0x6e, 0x64, 0x6f, 0x77, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6e, 0x65, 0x78, 0x74, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2f, 0x6e, 0x65, 0x78,
	0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65,
	0x2f, 0x63, 0x69, 0x72, 0x63, 0x75, 0x69, 0x74, 0x62, 0x72, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x2f,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_middleware_circuitbreaker_v1_circuitbreaker_proto_rawDescOnce sync.Once
	file_middleware_circuitbreaker_v1_circuitbreaker_proto_rawDescData = file_middleware_circuitbreaker_v1_circuitbreaker_proto_rawDesc
)

func file_middleware_circuitbreaker_v1_circuitbreaker_proto_rawDescGZIP() []byte {
	file_middleware_circuitbreaker_v1_circuitbreaker_proto_rawDescOnce.Do(func() {
		file_middleware_circuitbreaker_v1_circuitbreaker_proto_rawDescData = protoimpl.X.CompressGZIP(file_middleware_circuitbreaker_v1_circuitbreaker_proto_rawDescData)
	})
	return file_middleware_circuitbreaker_v1_circuitbreaker_proto_rawDescData
}

var file_middleware_circuitbreaker_v1_circuitbreaker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_middleware_circuitbreaker_v1_circuitbreaker_proto_goTypes = []interface{}{
	(*CircuitBreaker)(nil),      // 0: next.middleware.circuitbreaker.v1.CircuitBreaker
	(*SuccessRatio)(nil),        // 1: next.middleware.circuitbreaker.v1.SuccessRatio
	(*durationpb.Duration)(nil), // 2: google.protobuf.Duration
}
var file_middleware_circuitbreaker_v1_circuitbreaker_proto_depIdxs = []int32{
	1, // 0: next.middleware.circuitbreaker.v1.CircuitBreaker.success_ratio:type_name -> next.middleware.circuitbreaker.v1.SuccessRatio
	2, // 1: next.middleware.circuitbreaker.v1.SuccessRatio.window:type_name -> google.protobuf.Duration
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_middleware_circuitbreaker_v1_circuitbreaker_proto_init() }
func file_middleware_circuitbreaker_v1_circuitbreaker_proto_init() {
	if File_middleware_circuitbreaker_v1_circuitbreaker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_middleware_circuitbreaker_v1_circuitbreaker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CircuitBreaker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_middleware_circuitbreaker_v1_circuitbreaker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuccessRatio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_middleware_circuitbreaker_v1_circuitbreaker_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*CircuitBreaker_SuccessRatio)(nil),
		(*CircuitBreaker_Ratio)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_middleware_circuitbreaker_v1_circuitbreaker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_middleware_circuitbreaker_v1_circuitbreaker_proto_goTypes,
		DependencyIndexes: file_middleware_circuitbreaker_v1_circuitbreaker_proto_depIdxs,
		MessageInfos:      file_middleware_circuitbreaker_v1_circuitbreaker_proto_msgTypes,
	}.Build()
	File_middleware_circuitbreaker_v1_circuitbreaker_proto = out.File
	file_middleware_circuitbreaker_v1_circuitbreaker_proto_rawDesc = nil
	file_middleware_circuitbreaker_v1_circuitbreaker_proto_goTypes = nil
	file_middleware_circuitbreaker_v1_circuitbreaker_proto_depIdxs = nil
}
