titleOnly: true
commitOnly: false
titleAndCommits: false
scopes:
  - api
  - config
  - broker
  - internal
  - middleware
  - pkg
  - runtime
  - transport
types:
  - deps
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert
